version: '3'

services:
  mongo:
    image: mongo:5.0
    container_name: mongo-dev
    restart: always
    volumes:
      - ./data/dev/mongo:/data/db
    networks:
      - dev-network
    ports:
      - "27017:27017"

networks:
  dev-network:
    driver: bridge
